use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason
config :gibs, GibsWeb.Endpoint,
  http: [port: System.get_env("HTTP_PORT") || 4000],
  https: [
    port: System.get_env("HTTPS_PORT") || 8000,
    cipher_suite: String.to_atom(System.get_env("HTTPS_CIPHER_SUITE")) || :strong,
    keyfile: System.get_env("HTTPS_KEY_FILE") || "priv/cert/selfsigned_key.pem",
    certfile: System.get_env("HTTPS_CERT_FILE") || "priv/cert/selfsigned.pem"
  ],
  secret_key_base:
    System.get_env("SECRET_KEY_BASE") ||
      "O4CFvDf/9yylAsysqpAC6pt89dy1XbbXX6eI5ti4Xk1ezokFiDyyfENqL4X0Lhk9",
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :gibs, GibsWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/gibs_web/views/.*(ex)$},
      ~r{lib/gibs_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Configure your database
config :gibs, Gibs.Repo,
  username: System.get_env("POSTGRES_USER"),
  password: System.get_env("POSTGRES_PASSWORD"),
  database: System.get_env("POSTGRES_DB"),
  hostname: System.get_env("POSTGRES_HOST"),
  pool_size: 10
