use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason
config :gibs, GibsWeb.Endpoint,
  http: [:inet6, port: System.get_env("HTTP_PORT") || 4000],
  https: [
    port: System.get_env("HTTPS_PORT") || 8000,
    cipher_suite: String.to_atom(System.get_env("HTTPS_CIPHER_SUITE")) || :strong,
    keyfile: System.get_env("HTTPS_KEY_FILE") || "priv/cert/selfsigned_key.pem",
    certfile: System.get_env("HTTPS_CERT_FILE") || "priv/cert/selfsigned.pem"
  ],
  url: [host: System.get_env("URL_HOST") || "example.com", port: System.get_env("URL_PORT") || 80],
  secret_key_base:
    System.get_env("SECRET_KEY_BASE") ||
      "O4CFvDf/9yylAsysqpAC6pt89dy1XbbXX6eI5ti4Xk1ezokFiDyyfENqL4X0Lhk9",
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Configure your database
config :gibs, Gibs.Repo,
  username: System.get_env("POSTGRES_USER"),
  password: System.get_env("POSTGRES_PASSWORD"),
  database: System.get_env("POSTGRES_DB"),
  hostname: System.get_env("POSTGRES_HOST"),
  pool_size: 15
